### ISSUE TITLE
Add `WithValidator` Option

### ISSUE THREAD

**Issue by h0rv** [instructor-ai/instructor-go#22]
Add support for https://github.com/go-playground/validator/.

- [ ] Add `WithValidator` Options
- [ ] Use validation errors for model to fix

**Comment by h0rv** [comment]
Unfortunately, there is no Go package like Pydantic that will do the Struct to JSON Schema mapping and validation all in one. But for now

`jsonschema` + `validator` seems like the best approach

**Comment by Sushmithamallesh** [comment]
Is the plan to be verifying the response in processResponse?

**Comment by h0rv** [comment]
> Is the plan to be verifying the response in processResponse?

@Sushmithamallesh I made some changes, so now there is a `chatHandler()` and `chatStreamHandler()` functions that handle all the calls from the providers to abstract that functionality out. We should create a `validate.go` file that holds this logic and calls it in both of these (if the flag is enabled)

**Comment by Sushmithamallesh** [comment]
Oh cool. I might end up picking this up today!

**Comment by h0rv** [comment]
> Oh cool. I might end up picking this up today!

Awesome - feel free to reach out on the Discord if you have any questions!
