### ISSUE TITLE
Update usage on failed json.Unmarshal or validate.Struct

### ISSUE THREAD

**Issue by ericvanlare** [instructor-ai/instructor-go#28]
Response usage for input tokens and output tokens is only counted when it comes from a chat with successful json hydration, usage counts for failures at `json.Unmarshal()` or `validate.Struct()` in `chat.go` are ignored as of now.

[Here's a reference I found in instructor-py](https://github.com/jxnl/instructor/blob/fe0d8bdf09655012733b6203d11d38f9b3b4a9f7/instructor/utils.py#L123)

I propose instructor-go should count usage from all LLM calls in the retry, successes and failures, and update the successful call's usage counts before returning it.

**Comment by ericvanlare** [comment]
Also in `i.chat()` there's an err nil check that returns a nil response, could it be changed to a response that's empty except for usage from the call for cases such as `chatToolCall()` where it will return err for no tool calls, but there was still usage?

**Comment by ericvanlare** [comment]
Created a PR [here](https://github.com/instructor-ai/instructor-go/pull/29), @h0rv if you have some time I would greatly appreciate a review on this 🙏 I'm keen to add instructor-go to my projects but accurate usage tracking is a hard requirement

**Comment by h0rv** [comment]
@ericvanlare Now the usage PR is merged, would you be able to add a separate PR to add a section in the README on how to view the usage, noting how the it sums the retries and you can still view the usage even if instructor fails in the end?
