### ISSUE TITLE
where is the instructor.RoleUser??

### ISSUE THREAD

**Issue by taosu0216** [instructor-ai/instructor-go#36]
using the function calling demo
![image](https://github.com/user-attachments/assets/5bd1020d-9d9c-47e1-931f-78d5b00cf348)
but goland show 
![image](https://github.com/user-attachments/assets/9e2d97b0-700f-43f8-b270-b1faa1a9482f)

**Comment by h0rv** [comment]
@taosu0216 Sorry, examples on the readme were out of date - just pushed a fix for them.

The up to date example can be found here: https://github.com/instructor-ai/instructor-go/blob/main/examples/function_calling/main.go.
